services:
  # Client application
  client:
    image: ${DOCKER_REGISTRY-}keepitup.magjob.client
    build:
      context: .
      dockerfile: src/KeepItUp.MagJob.Client/Dockerfile
    ports:
      - "80:80"

  # Gateway
  apigateway:
    image: ${DOCKER_REGISTRY-}keepitup.magjob.apigateway
    build:
      context: .
      dockerfile: src/KeepItUp.MagJob.APIGateway/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_URLS=http://+:80

  # Microservices
  identity:
    image: ${DOCKER_REGISTRY-}keepitup.magjob.identity
    build:
      context: .
      dockerfile: src/KeepItUp.MagJob.Identity/Dockerfile
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_URLS=http://+:80
      - KeycloakAdmin__ClientSecret=pGKFGTy8hVmKubkeGOeOvNu3dsFTKJQO
      - KeycloakAdmin__ServerUrl=http://keycloak:8080
      - ConnectionStrings__DefaultConnection=Host=magjob.database;Database=magjob;Username=postgres;Password=postgres
    depends_on:
      - magjob.database
      - keycloak

  # chat:
  #   image: ${DOCKER_REGISTRY-}keepitup.magjob.chat
  #   build:
  #     context: .
  #     dockerfile: src/KeepItUp.MagJob.Chat/Dockerfile
  #   ports:
  #     - "5004:80"
  #   environment:
  #   depends_on:
  #     - magjob.database
  #     - keycloak

  # calendar:
  #   image: ${DOCKER_REGISTRY-}keepitup.magjob.calendar
  #   build:
  #     context: .
  #     dockerfile: src/KeepItUp.MagJob.Calendar/Dockerfile
  #   ports:
  #     - "5006:80"
  #   environment:
  #   depends_on:
  #     - magjob.database
  #     - keycloak

  # timeEvidence:
  #   image: ${DOCKER_REGISTRY-}keepitup.magjob.timeEvidence
  #   build:
  #     context: .
  #     dockerfile: src/KeepItUp.MagJob.TimeEvidence/Dockerfile
  #   ports:
  #     - "5008:80"
  #   environment:
  #   depends_on:
  #     - magjob.database
  #     - keycloak

  # Keycloak (Identity Server)
  keycloak:
    image: quay.io/keycloak/keycloak:26.1
    command: start-dev --import-realm
    ports:
      - "18080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL_HOST=keycloak.database
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=postgres
    volumes:
      - ./src/Keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
      - ./src/Keycloak/themes/magjob:/opt/keycloak/themes/magjob
    depends_on:
      - keycloak.database

  # Databases
  keycloak.database:
    image: postgres:17.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: keycloak
    volumes:
      - ${APPDATA}/KeepItUp.MagJob/db/keycloak:/var/lib/postgresql/data

  magjob.database:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: KeepItUp.MagJob
    volumes:
      - ${APPDATA}/KeepItUp.MagJob/db/magjob:/var/lib/postgresql/data
