using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace KeepItUp.MagJob.Identity.Infrastructure.Data.Migrations;

/// <inheritdoc />
public partial class UpdateContributorModel : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropColumn(
            name: "Permissions",
            schema: "identity",
            table: "Users");

        migrationBuilder.AddColumn<string>(
            name: "BannerUrl",
            schema: "identity",
            table: "Organizations",
            type: "text",
            nullable: true);

        migrationBuilder.AddColumn<string>(
            name: "LogoUrl",
            schema: "identity",
            table: "Organizations",
            type: "text",
            nullable: true);

        // First, ensure the uuid-ossp extension is created
        migrationBuilder.Sql("CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\";");

        // Drop the IDENTITY property first
        migrationBuilder.Sql("ALTER TABLE identity.\"Contributors\" ALTER COLUMN \"Id\" DROP IDENTITY IF EXISTS;");

        // Use raw SQL with explicit USING clause to convert integer to UUID
        migrationBuilder.Sql("ALTER TABLE identity.\"Contributors\" ALTER COLUMN \"Id\" TYPE uuid USING (uuid_generate_v4());");

        // Set a default for future inserts
        migrationBuilder.Sql("ALTER TABLE identity.\"Contributors\" ALTER COLUMN \"Id\" SET DEFAULT uuid_generate_v4();");

        // Add CreatedAt column
        migrationBuilder.AddColumn<DateTime>(
            name: "CreatedAt",
            schema: "identity",
            table: "Contributors",
            type: "timestamp with time zone",
            nullable: false,
            defaultValue: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

        // Add UpdatedAt column
        migrationBuilder.AddColumn<DateTime>(
            name: "UpdatedAt",
            schema: "identity",
            table: "Contributors",
            type: "timestamp with time zone",
            nullable: true);
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropColumn(
            name: "BannerUrl",
            schema: "identity",
            table: "Organizations");

        migrationBuilder.DropColumn(
            name: "LogoUrl",
            schema: "identity",
            table: "Organizations");

        migrationBuilder.DropColumn(
            name: "CreatedAt",
            schema: "identity",
            table: "Contributors");

        migrationBuilder.DropColumn(
            name: "UpdatedAt",
            schema: "identity",
            table: "Contributors");

        migrationBuilder.AddColumn<List<string>>(
            name: "Permissions",
            schema: "identity",
            table: "Users",
            type: "text[]",
            nullable: false);

        // Remove the default UUID generation
        migrationBuilder.Sql("ALTER TABLE identity.\"Contributors\" ALTER COLUMN \"Id\" DROP DEFAULT;");

        // Change back to integer type (if there's existing data, this might fail)
        migrationBuilder.Sql("ALTER TABLE identity.\"Contributors\" ALTER COLUMN \"Id\" TYPE integer USING (1);");

        // Add back the identity property
        migrationBuilder.Sql("ALTER TABLE identity.\"Contributors\" ALTER COLUMN \"Id\" ADD GENERATED BY DEFAULT AS IDENTITY;");
    }
}
