import { provideIcons } from '@ng-icons/core';
import {
  heroArrowRight,
  heroMagnifyingGlass,
  heroEnvelope,
  heroUser,
  heroUsers,
  heroClipboardDocument,
  heroChartBar,
  heroBolt,
  heroQuestionMarkCircle,
  heroChevronRight,
  heroSun,
  heroMoon,
  heroUserGroup,
  heroDocumentText,
  heroChartPie,
  heroHome,
  heroBars3,
  heroXMark,
  heroEllipsisVertical,
  heroArrowLeftOnRectangle,
  heroArrowRightOnRectangle,
  heroCog,
  heroBell,
} from '@ng-icons/heroicons/outline';

export const heroIcons = provideIcons({
  heroArrowRight,
  heroMagnifyingGlass,
  heroEnvelope,
  heroUser,
  heroUsers,
  heroClipboardDocument,
  heroChartBar,
  heroBolt,
  heroQuestionMarkCircle,
  heroChevronRight,
  heroSun,
  heroMoon,
  heroUserGroup,
  heroDocumentText,
  heroChartPie,
  heroHome,
  heroBars3,
  heroXMark,
  heroEllipsisVertical,
  heroArrowLeftOnRectangle,
  heroArrowRightOnRectangle,
  heroCog,
  heroBell,
});
